GET http://localhost:8000/

###

GET http://localhost:8000/todos

###

GET http://localhost:8000/todos/<id>

###

POST http://localhost:8000/todos
content-type: application/json

{
    "title": "Feed 🦕"
}

###

PUT http://localhost:8000/todos/<id>
content-type: application/json

{
    "done": true
}

###

DELETE http://localhost:8000/todos/<id>
content-type: application/json
